apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: odds
  source:
    path: applications
    repoURL: https://github.com/avenging/argocd-apps.git
    targetRevision: HEAD